### GET /
GET http://localhost:3000/

### GET /healthcheck
GET http://localhost:3000/healthcheck

### GET Books
GET http://localhost:3000/books

### POST books - Teste simples - Livro 00-000-0000-0
POST http://localhost:3000/books HTTP/1.1
Content-Type: application/json

{
   "sbn":"00-000-0000-0",
   "name":"Um livro qualquer", 
   "description":"Uma descrição qualquer",
   "author":"Alan",
   "stock":15
}

### GET 00-000-0000-0
GET http://localhost:3000/books/00-000-0000-0

### POST books - Teste semi real - Livro 85-359-0277-5
POST http://localhost:3000/books HTTP/1.1
Content-Type: application/json

{
   "sbn":"85-359-0277-5",
   "name":"Autobiografia de Alan",
   "description":"Uma perspectiva sobre Alan Wesley",
   "author":"Alan",
   "stock":10
}

### GET 85-359-0277-5
GET http://localhost:3000/books/85-359-0277-5

### Search "Autobiografia"
GET http://localhost:3000/books/search?q=Autobiografia

### GET Paginado
GET http://localhost:3000/books?page=1&limit=10

### PUT books - Atualiza Livro 00-000-0000-0
PUT http://localhost:3000/books/00-000-0000-0 HTTP/1.1
Content-Type: application/json

{
   "name": "Um livro qualquer 2"
}

### PUT books - Tenta atualizar SBN do livro 00-000-0000-0
PUT http://localhost:3000/books/00-000-0000-0 HTTP/1.1
Content-Type: application/json

{
   "sbn":"00-000-0000-1"
}

### DELETE book - Deleta Livro 00-000-0000-0
DELETE http://localhost:3000/books/00-000-0000-0 HTTP/1.1

### DELETE book - Deleta Livro 85-359-0277-5
DELETE http://localhost:3000/books/85-359-0277-5 HTTP/1.1

### DELETE book - Tenta deletar SBN inexistente
DELETE http://localhost:3000/books/00-000-0000-1 HTTP/1.1